//test factory functions for creating common test objects
//provides clean, reusable setup patterns for tests

import Player from "../../backend/gameSetup/Player.js";
import GameSession from "../../backend/gameSetup/gameSession.js";
import SessionManager from "../../backend/gameSetup/SessionManager.js";

//factory for creating test players with default or custom properties
export function createTestPlayer(username = "testuser", socketId = "socket123", colour = null) {
  return new Player(username, socketId, colour);
}

//factory for creating a game session with players already set up
//eliminates the manual property assignment seen in current tests
export function createGameSessionWithPlayers(players = []) {
  const session = new GameSession();
  //gameSessionID is auto-generated by GameSession constructor
  session.connectedPlayersSocketIDs = { players: {} };
  
  //add players to the session using proper setup
  players.forEach((playerConfig, index) => {
    const { username, socketId, colour } = playerConfig;
    const player = createTestPlayer(username, socketId, colour);
    
    //add to legacy structure for backwards compatibility
    session.connectedPlayersSocketIDs.players[socketId] = player;
    
    //add to connectedUsers (single source of truth)
    session.addPlayerToSession(player);
  });
  
  //create game instance if players exist
  if (players.length > 0) {
    session.createGameInstance();
    session.gameInstance.createNewChessGame();
  }
  
  return session;
}

//factory for setting up a complete test scenario with session manager, session, and players
export function createTestScenario(playerConfigs = []) {
  const sessionManager = new SessionManager();
  const session = createGameSessionWithPlayers(playerConfigs);
  
  //add session to manager
  sessionManager.addSession(session.gameSessionID, session);
  
  //map players to session
  playerConfigs.forEach(config => {
    const player = createTestPlayer(config.username, config.socketId, config.colour);
    sessionManager.addPlayer(config.socketId, player);
    sessionManager.mapSocketToSession(config.socketId, session.gameSessionID);
  });
  
  return {
    sessionManager,
    session,
    sessionId: session.gameSessionID
  };
}

//predefined player configurations for common test scenarios
export const TEST_PLAYERS = {
  //chess game with black and white players
  CHESS_FULL_GAME: [
    { username: "blackplayer", socketId: "socket_black", colour: "black" },
    { username: "whiteplayer", socketId: "socket_white", colour: "white" }
  ],
  
  //chess game with only one player waiting
  CHESS_WAITING_GAME: [
    { username: "waitingplayer", socketId: "socket_waiting", colour: "black" }
  ],
  
  //empty game (no players)
  EMPTY_GAME: []
};

//factory for creating multiple test sessions for testing game listing functionality
export function createMultipleTestSessions(sessionConfigs = []) {
  const sessionManager = new SessionManager();
  const sessions = [];
  
  sessionConfigs.forEach(config => {
    const { playerConfigs = [], sessionId = null } = config;
    const session = createGameSessionWithPlayers(playerConfigs);
    
    if (sessionId) {
      session.gameSessionID = sessionId;
    }
    
    sessionManager.addSession(session.gameSessionID, session);
    
    //set up player mappings
    playerConfigs.forEach(playerConfig => {
      const player = createTestPlayer(playerConfig.username, playerConfig.socketId, playerConfig.colour);
      sessionManager.addPlayer(playerConfig.socketId, player);
      sessionManager.mapSocketToSession(playerConfig.socketId, session.gameSessionID);
    });
    
    sessions.push(session);
  });
  
  return { sessionManager, sessions };
}