/**
 * Test factory functions for creating common test objects
 * Provides clean, reusable setup patterns for tests
 */

import Player from "../../backend/gameSetup/Player.js";
import GameSession from "../../backend/gameSetup/gameSession.js";
import SessionManager from "../../backend/gameSetup/SessionManager.js";
import Board from "../../chessCore/gameLogic/board.js";
import GameStateManager from "../../chessCore/gameLogic/GameStateManager.js";

/**
 * @typedef {Object} BoardConfig
 * @property {boolean} [withPieces=true] whether to place pieces after creating an empty board
 *
 * @typedef {Object} CreateGameStateOptions
 * @property {'white'|'black'} [startingColour='black']
 * @property {Board} [board]
 * @property {BoardConfig} [boardConfig]
 */

/**
 * Creates a test chess board.
 * Defaults: withPieces=true
 * @param {BoardConfig} [boardConfig]
 * @returns {Board}
 */
export function createTestBoard(boardConfig = {}) {
  const { withPieces = true } = boardConfig;
  const board = new Board();
  board.createEmptyBoard();
  if (withPieces) {
    board.initialisePieces();
  }
  return board;
}

/**
 * Creates a game state manager and its board.
 * Defaults: startingColour="black", board created if not provided, boardConfig={}
 * @param {CreateGameStateOptions} [options]
 * @returns {{ board: Board, gameStateManager: GameStateManager }}
 */
export function createTestGameState(options = {}) {
  const {
    startingColour = "black",
    board: providedBoard = null,
    boardConfig = {},
  } = options;

  let board = providedBoard;
  if (!board) {
    board = createTestBoard(boardConfig);
  }
  const gameStateManager = new GameStateManager(board, startingColour);
  return { board, gameStateManager };
}

/**
 * Factory for creating test players with default or custom properties
 * @param {string} username - Player username, defaults to "testuser"
 * @param {string} socketId - Socket ID, defaults to "socket123"
 * @param {string|null} colour - Player color, defaults to null
 * @returns {Player} New Player instance for testing
 */
export function createTestPlayer(
  username = "testuser",
  socketId = "socket123",
  colour = null
) {
  return new Player(username, socketId, colour);
}

/**
 * Factory for creating a game session with players already set up
 * Eliminates the manual property assignment seen in current tests
 * @param {Object[]} players - Array of player configuration objects
 * @returns {GameSession} Configured GameSession with players added
 */
export function createGameSessionWithPlayers(players = []) {
  const session = new GameSession();
  //gameSessionID is auto-generated by GameSession constructor
  //add players to the session using proper setup
  players.forEach((playerConfig, index) => {
    const { username, socketId, colour } = playerConfig;
    const player = createTestPlayer(username, socketId, colour);

    //add to connectedUsers (single source of truth)
    session.addPlayerToSession(player);
  });

  //create game instance if players exist
  if (players.length > 0) {
    session.createGameInstance();
    session.gameInstance.createNewChessGame();
  }

  return session;
}

/**
 * Factory for setting up a complete test scenario with session manager, session, and players
 * @param {Object[]} playerConfigs - Array of player configuration objects (use TEST_PLAYERS constants)
 * @returns {{sessionManager: SessionManager, session: GameSession, sessionId: string}} Complete test scenario
 */
export function createTestScenario(playerConfigs = []) {
  const sessionManager = new SessionManager();
  const session = createGameSessionWithPlayers(playerConfigs);

  //add session to manager
  sessionManager.addSession(session.gameSessionID, session);

  //register existing session players in manager for networking lookups
  session.connectedUsers.forEach((player) => {
    if (!player || !player.socketID) {
      return;
    }
    sessionManager.addPlayer(player.socketID, player);
    sessionManager.mapSocketToSession(player.socketID, session.gameSessionID);
  });

  return {
    sessionManager,
    session,
    sessionId: session.gameSessionID,
  };
}

/**
 * Predefined player configurations for common test scenarios
 * @readonly
 */
export const TEST_PLAYERS = {
  //chess game with black and white players
  CHESS_FULL_GAME: [
    { username: "blackplayer", socketId: "socket_black", colour: "black" },
    { username: "whiteplayer", socketId: "socket_white", colour: "white" },
  ],

  //chess game with only one player waiting
  CHESS_WAITING_GAME: [
    { username: "waitingplayer", socketId: "socket_waiting", colour: "black" },
  ],

  //empty game (no players)
  EMPTY_GAME: [],
};

/**
 * Factory for creating multiple test sessions for testing game listing functionality
 * @param {Object[]} sessionConfigs - Array of session configuration objects
 * @returns {{sessionManager: SessionManager, sessions: GameSession[]}} Session manager with multiple sessions
 */
export function createMultipleTestSessions(sessionConfigs = []) {
  const sessionManager = new SessionManager();
  const sessions = [];

  sessionConfigs.forEach((config) => {
    const { playerConfigs = [], sessionId = null } = config;
    const session = createGameSessionWithPlayers(playerConfigs);

    if (sessionId) {
      session.gameSessionID = sessionId;
    }

    sessionManager.addSession(session.gameSessionID, session);

    //set up player mappings
    playerConfigs.forEach((playerConfig) => {
      const player = createTestPlayer(
        playerConfig.username,
        playerConfig.socketId,
        playerConfig.colour
      );
      sessionManager.addPlayer(playerConfig.socketId, player);
      sessionManager.mapSocketToSession(
        playerConfig.socketId,
        session.gameSessionID
      );
    });

    sessions.push(session);
  });

  return { sessionManager, sessions };
}
